# Generated by Django 5.2.13 on 2026-04-22 13:34

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(max_length=64, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='客户名称')),
                ('description', models.TextField(blank=True, verbose_name='项目备注')),
                ('status', models.CharField(choices=[('in_progress', '处理中'), ('pending_feedback', '待前端确认'), ('closed', '已关闭')], default='in_progress', max_length=32, verbose_name='状态')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='指派时间')),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True, verbose_name='提交待确认时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to=settings.AUTH_USER_MODEL, verbose_name='提单人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('detail', models.TextField(blank=True, verbose_name='需求详情')),
                ('difficulty', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=16, verbose_name='难度')),
                ('due_at', models.DateTimeField(verbose_name='期望完成时间')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('doing', '处理中'), ('done', '已完成'), ('rejected', '被打回')], default='pending', max_length=16, verbose_name='状态')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tickets.ticket', verbose_name='所属工单')),
            ],
            options={
                'verbose_name': '需求条目',
                'verbose_name_plural': '需求条目',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='内容')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='跳转地址')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('input', '客户输入'), ('deliverable', '交付结果')], max_length=16, verbose_name='类型')),
                ('file', models.FileField(upload_to=tickets.models.ticket_attachment_upload_to, verbose_name='文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='工单')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='内容')),
                ('is_reject_reason', models.BooleanField(default=False, verbose_name='是否打回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('submitted', '创建工单'), ('assigned', '分派'), ('req_done', '需求完成'), ('req_reopened', '需求重置'), ('sent_for_review', '提交待确认'), ('rejected', '前端打回'), ('closed', '关闭工单'), ('reopened', '重新打开工单'), ('commented', '评论'), ('attached', '上传附件')], max_length=32, verbose_name='类型')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='tickets_tic_assigne_e36302_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='tickets_not_recipie_a596ee_idx'),
        ),
    ]
