# Generated by Django 5.2.13 on 2026-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_requirement_to_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='前端确认时间'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='后端完成时间'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('doing', '处理中'), ('done', '后端已完成'), ('accepted', '前端已确认'), ('rejected', '被打回')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='ticketevent',
            name='kind',
            field=models.CharField(choices=[('submitted', '创建工单'), ('assigned', '分派'), ('req_done', '需求完成'), ('req_accepted', '前端确认需求'), ('req_sent_back', '前端打回需求'), ('req_reopened', '需求重置'), ('sent_for_review', '提交待确认'), ('rejected', '前端打回工单'), ('closed', '关闭工单'), ('reopened', '重新打开工单'), ('commented', '评论'), ('attached', '上传附件')], max_length=32, verbose_name='类型'),
        ),
    ]
