# Generated by Django 5.2.13 on 2026-04-23 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_req_accepted_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="project_no",
            field=models.CharField(db_index=True, max_length=64, verbose_name="项目编号"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["project_no"], name="tickets_tic_project_aaa83d_idx"
            ),
        ),
    ]
